#!/usr/bin/env bash
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail
set -Eeuo pipefail
# cd to script location
cd "$(dirname "${BASH_SOURCE[0]}")"
cd ..


export TMP=$(mktemp -d)

find migrations \
 | entr -cnr bash -c "scripts/sorted_schema > '$TMP/schema-new.sql' && git diff --no-index --color-words schema.sql '$TMP'/schema-new.sql | cat"
