name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

# automatically cancel previous runs on the same PR
# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      RUSTFLAGS: --deny warnings # fatal warnings
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout/issues/626
          # This is correct, because we're using a merge queue which only merges when built against the latest target branch.
          # https://docs.mergify.com/actions/queue/
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust build cache
        uses: Swatinem/rust-cache@v2

      - name: Install tools
        run: cargo install sqlx-cli

      - name: load envrc
        uses: HatsuneMiku3939/direnv-action@99d45b70ef95201986f2094cec9b625f1e28347b # pin@v1

      - name: Migrate database
        run: |
          sqlx database create
          sqlx migrate run

      - name: Validate current schema
        run: cmp -s <(sqlite3 -init /dev/null data/data.sqlite '.schema') schema.sql

      - name: Validate sqlx offline mode data
        run: cargo sqlx prepare --check --merged

      - name: cargo clippy (no features)
        # clippy also includes all warnings from cargo check
        run: cargo --locked clippy --workspace --all-targets --no-default-features

      - name: cargo clippy (all features)
        # clippy also includes all warnings from cargo check
        run: cargo --locked clippy --workspace --all-targets --all-features

      - name: cargo test
        run: cargo --locked test --workspace --all-targets --all-features

      - name: cargo fmt --check
        run: cargo --locked fmt --check

      - name: Start webserver in background
        run: |
          set -e
          make -C sqlite-vector
          cargo --locked build
          export OPENAI_API_KEY=foooooooooooo # fake, but enough to pass tests!
          target/debug/propolis > /tmp/background_output 2>&1 &
          sleep 1
          kill -0 $! || (cat /tmp/background_output && exit 1) # check if background process is still running

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Docker build
        run: docker build .

  deploy:
      needs: build
      if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
      name: Deploy app
      runs-on: ubuntu-22.04
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      timeout-minutes: 30
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --local-only
